
set_property IOSTANDARD LVCMOS33 [get_ports BR_MCU]
set_property IOSTANDARD LVCMOS33 [get_ports Clock_22_5792]
set_property IOSTANDARD LVCMOS33 [get_ports Clock_24_576]
set_property IOSTANDARD LVCMOS33 [get_ports COAX_IN_FPGA]
set_property IOSTANDARD LVCMOS33 [get_ports DSD_A]
set_property IOSTANDARD LVCMOS33 [get_ports DSD_A_N]
set_property IOSTANDARD LVCMOS33 [get_ports DSD_B]
set_property IOSTANDARD LVCMOS33 [get_ports DSD_B_N]
set_property IOSTANDARD LVCMOS33 [get_ports DSD_CLK]
set_property IOSTANDARD LVCMOS33 [get_ports DSD_EN]
set_property IOSTANDARD LVCMOS33 [get_ports DSP_SEL]
set_property IOSTANDARD LVCMOS33 [get_ports HDMI_DATA]
set_property IOSTANDARD LVCMOS33 [get_ports HDMI_FCLK]
set_property IOSTANDARD LVCMOS33 [get_ports HDMI_LRCLK]
set_property IOSTANDARD LVCMOS33 [get_ports L_BCLK]
set_property IOSTANDARD LVCMOS33 [get_ports L_CLK]
set_property IOSTANDARD LVCMOS33 [get_ports L_DATA_N]
set_property IOSTANDARD LVCMOS33 [get_ports L_DATA_P]
set_property IOSTANDARD LVCMOS33 [get_ports LED1]
set_property IOSTANDARD LVCMOS33 [get_ports LED2]
set_property IOSTANDARD LVCMOS33 [get_ports LED3]
set_property IOSTANDARD LVCMOS33 [get_ports OPTICAL_IN_1]
set_property IOSTANDARD LVCMOS33 [get_ports OPTICAL_IN_2]
set_property IOSTANDARD LVCMOS33 [get_ports R_BCLK]
set_property IOSTANDARD LVCMOS33 [get_ports R_CLK]
set_property IOSTANDARD LVCMOS33 [get_ports R_DATA_N]
set_property IOSTANDARD LVCMOS33 [get_ports R_DATA_P]
set_property IOSTANDARD LVCMOS33 [get_ports RCLK_ON]
set_property IOSTANDARD LVCMOS33 [get_ports SPDIF_CLK]
set_property IOSTANDARD LVCMOS33 [get_ports SPDIF_DATA]
set_property IOSTANDARD LVCMOS33 [get_ports SPDIF_LOCK]
set_property IOSTANDARD LVCMOS33 [get_ports SPDIF_LRCLK]
set_property IOSTANDARD LVCMOS33 [get_ports XMOS_DATA]
set_property IOSTANDARD LVCMOS33 [get_ports XMOS_DSDON]
set_property IOSTANDARD LVCMOS33 [get_ports XMOS_F0]
set_property IOSTANDARD LVCMOS33 [get_ports XMOS_F0_MCU]
set_property IOSTANDARD LVCMOS33 [get_ports XMOS_F1]
set_property IOSTANDARD LVCMOS33 [get_ports XMOS_F1_MCU]
set_property IOSTANDARD LVCMOS33 [get_ports XMOS_F2]
set_property IOSTANDARD LVCMOS33 [get_ports XMOS_F2_MCU]
set_property IOSTANDARD LVCMOS33 [get_ports XMOS_F3]
set_property IOSTANDARD LVCMOS33 [get_ports XMOS_F3_MCU]
set_property IOSTANDARD LVCMOS33 [get_ports XMOS_FCLK]
set_property IOSTANDARD LVCMOS33 [get_ports XMOS_LRCLK]
set_property PACKAGE_PIN V4 [get_ports BR_MCU]
set_property PACKAGE_PIN F4 [get_ports COAX_IN_FPGA]
set_property PACKAGE_PIN A1 [get_ports DSD_A]
set_property PACKAGE_PIN B4 [get_ports DSD_A_N]
set_property PACKAGE_PIN B3 [get_ports DSD_B]
set_property PACKAGE_PIN A4 [get_ports DSD_B_N]
set_property PACKAGE_PIN B2 [get_ports DSD_CLK]
set_property PACKAGE_PIN A3 [get_ports DSD_EN]
set_property PACKAGE_PIN N2 [get_ports DSP_SEL]
set_property PACKAGE_PIN E1 [get_ports HDMI_DATA]
set_property PACKAGE_PIN P4 [get_ports HDMI_FCLK]
set_property PACKAGE_PIN P5 [get_ports HDMI_LRCLK]
set_property PACKAGE_PIN G2 [get_ports L_CLK]
set_property PACKAGE_PIN G1 [get_ports L_BCLK]
set_property PACKAGE_PIN F1 [get_ports L_DATA_N]
set_property PACKAGE_PIN H2 [get_ports L_DATA_P]
set_property PACKAGE_PIN A16 [get_ports LED1]
set_property PACKAGE_PIN A15 [get_ports LED2]
set_property PACKAGE_PIN A14 [get_ports LED3]
set_property PACKAGE_PIN J2 [get_ports OPTICAL_IN_1]
set_property PACKAGE_PIN E2 [get_ports R_BCLK]
set_property PACKAGE_PIN B1 [get_ports R_CLK]
set_property PACKAGE_PIN C2 [get_ports R_DATA_N]
set_property PACKAGE_PIN C1 [get_ports R_DATA_P]
set_property PACKAGE_PIN U14 [get_ports RCLK_ON]
set_property PACKAGE_PIN J17 [get_ports SPDIF_DATA]
set_property PACKAGE_PIN G16 [get_ports SPDIF_CLK]
set_property PACKAGE_PIN A13 [get_ports SPDIF_LOCK]
set_property PACKAGE_PIN D15 [get_ports SPDIF_LRCLK]
set_property PACKAGE_PIN E17 [get_ports XMOS_DATA]
set_property PACKAGE_PIN J18 [get_ports XMOS_DSDON]
set_property PACKAGE_PIN H17 [get_ports XMOS_F0]
set_property PACKAGE_PIN G17 [get_ports XMOS_F1]
set_property PACKAGE_PIN G18 [get_ports XMOS_F2]
set_property PACKAGE_PIN F18 [get_ports XMOS_F3]
set_property PACKAGE_PIN V15 [get_ports XMOS_F0_MCU]
set_property PACKAGE_PIN V16 [get_ports XMOS_F1_MCU]
set_property PACKAGE_PIN F15 [get_ports XMOS_F2_MCU]
set_property PACKAGE_PIN F16 [get_ports XMOS_F3_MCU]
set_property PACKAGE_PIN C15 [get_ports XMOS_FCLK]
set_property PACKAGE_PIN H16 [get_ports XMOS_LRCLK]


set_property PACKAGE_PIN F3 [get_ports OPTICAL_IN_2]
set_property PACKAGE_PIN K2 [get_ports MCU_NRST]
set_property IOSTANDARD LVCMOS33 [get_ports MCU_NRST]
set_property IOSTANDARD LVCMOS33 [get_ports HDMI_MCLK]
set_property PACKAGE_PIN L1 [get_ports HDMI_MCLK]
set_property PACKAGE_PIN T5 [get_ports Clock_22_5792]
set_property PACKAGE_PIN R16 [get_ports Clock_24_576]

set_property IOSTANDARD LVCMOS33 [get_ports {SPDIF_XMOS_SEL[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SPDIF_XMOS_SEL[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SPDIF_XMOS_SEL[0]}]
set_property PACKAGE_PIN U17 [get_ports {SPDIF_XMOS_SEL[2]}]
set_property PACKAGE_PIN A5 [get_ports {SPDIF_XMOS_SEL[1]}]
set_property PACKAGE_PIN L18 [get_ports {SPDIF_XMOS_SEL[0]}]

set_property CONFIG_MODE SPIx4 [current_design]
set_property BITSTREAM.CONFIG.CONFIGRATE 33 [current_design]


set_property IOSTANDARD LVCMOS33 [get_ports {STM32_DATA[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {STM32_DATA[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {STM32_DATA[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {STM32_DATA[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {STM32_DATA[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {STM32_DATA[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {STM32_DATA[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {STM32_DATA[0]}]


set_property PACKAGE_PIN T18 [get_ports {STM32_DATA[7]}]
set_property PACKAGE_PIN R18 [get_ports {STM32_DATA[6]}]
set_property PACKAGE_PIN N16 [get_ports {STM32_DATA[5]}]
set_property PACKAGE_PIN P18 [get_ports {STM32_DATA[3]}]
set_property PACKAGE_PIN N17 [get_ports {STM32_DATA[2]}]
set_property PACKAGE_PIN M16 [get_ports {STM32_DATA[1]}]
set_property PACKAGE_PIN M17 [get_ports {STM32_DATA[0]}]
set_property PACKAGE_PIN P17 [get_ports {STM32_DATA[4]}]


set_property IOSTANDARD LVCMOS33 [get_ports I2S_BCLK_TEST]
set_property IOSTANDARD LVCMOS33 [get_ports I2S_LRCLK_TEST]
set_property PACKAGE_PIN A18 [get_ports I2S_BCLK_TEST]
set_property PACKAGE_PIN D18 [get_ports I2S_LRCLK_TEST]




set_property IOSTANDARD LVCMOS33 [get_ports STM32_CLK_TEST]
set_property PACKAGE_PIN E18 [get_ports STM32_CLK_TEST]


set_property IOSTANDARD LVCMOS33 [get_ports STM32_EN_TEST]
set_property PACKAGE_PIN D17 [get_ports STM32_EN_TEST]



set_property PACKAGE_PIN M2 [get_ports STM32_SR_STB]
set_property IOSTANDARD LVCMOS33 [get_ports STM32_SR_STB]

set_property PACKAGE_PIN M1 [get_ports SR_FAM_IN]
set_property IOSTANDARD LVCMOS33 [get_ports SR_FAM_IN]

#set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets {clk98_ibuf}]


set_property PACKAGE_PIN P15 [get_ports Clock_SI]
set_property IOSTANDARD LVCMOS33 [get_ports Clock_SI]
set_property PACKAGE_PIN E3 [get_ports Clock_SI_50MHZ]
set_property IOSTANDARD LVCMOS33 [get_ports Clock_SI_50MHZ]





set_property PACKAGE_PIN U18 [get_ports STM32_ACK]
set_property PACKAGE_PIN V5 [get_ports STM32_REQ]
set_property PACKAGE_PIN V17 [get_ports STM32_VALID]
set_property IOSTANDARD LVCMOS33 [get_ports STM32_ACK]
set_property IOSTANDARD LVCMOS33 [get_ports STM32_REQ]
set_property IOSTANDARD LVCMOS33 [get_ports STM32_VALID]

set_property IOSTANDARD LVCMOS33 [get_ports STM32_EN]
set_property PACKAGE_PIN V2 [get_ports STM32_EN]
